### PR TITLE
feat: add difficulty suggester

### PR DESCRIPTION
**Pull request by vaeng**
I don't know if this is very useful in the current state of the track, but I liked the challenge and made a difficulty-suggester utility that can provide markdown, plain, and JSON suggestions for the exercises on the track.

The heuristic I used is the frequency of the glyphs used across all the other exercises and the option to mark some glyphs as more complex in their usage to make the results more precise. If the results are nice, someone can use the JSON to integrate into the config file.

The current output looks like this:

| Exercise | Difficulty | Unique Tokens | Rarity Range |
|----------|------------|---------------|--------------|
| leap | 1 | 4 | (1.2142857142857144, 4.636363636363636) |
| hello-world | 1 | 0 | (0, 0) |
| rna-transcription | 1 | 2 | (1.02, 5.1) |
| gigasecond | 1 | 3 | (1.2142857142857144, 5.666666666666666) |
| resistor-color | 1 | 3 | (1.8214285714285712, 3.9230769230769234) |
| reverse-string | 2 | 3 | (1.02, 10.2) |
| collatz-conjecture | 2 | 9 | (0.5862068965517242, 5.1) |
| difference-of-squares | 2 | 6 | (1.2142857142857144, 7.285714285714285) |
| house | 2 | 11 | (0.5862068965517242, 3.6428571428571423) |
| two-fer | 2 | 6 | (0.5862068965517242, 8.5) |
| eliuds-eggs | 2 | 3 | (1.2142857142857144, 17.0) |
| nucleotide-count | 2 | 6 | (1.02, 10.2) |
| grains | 2 | 9 | (0.5862068965517242, 7.285714285714285) |
| acronym | 2 | 6 | (1.3421052631578947, 7.285714285714285) |
| scrabble-score | 2 | 6 | (1.02, 5.666666666666666) |
| resistor-color-duo | 2 | 8 | (1.2142857142857144, 8.5) |
| matrix | 3 | 9 | (0.5862068965517242, 12.75) |
| hamming | 3 | 9 | (0.5862068965517242, 10.2) |
| armstrong-numbers | 3 | 10 | (0.5862068965517242, 8.5) |
| proverb | 3 | 9 | (0.5862068965517242, 12.75) |
| pascals-triangle | 3 | 15 | (0.5862068965517242, 12.75) |
| rotational-cipher | 3 | 13 | (0.5862068965517242, 12.75) |
| resistor-color-trio | 3 | 15 | (0.5862068965517242, 8.5) |
| diamond | 3 | 13 | (0.5862068965517242, 7.285714285714285) |
| bob | 3 | 14 | (0.5862068965517242, 12.75) |
| darts | 3 | 9 | (0.5862068965517242, 25.5) |
| high-scores | 4 | 9 | (0.5862068965517242, 25.5) |
| secret-handshake | 4 | 13 | (0.5862068965517242, 17.0) |
| series | 4 | 12 | (0.5862068965517242, 12.75) |
| luhn | 4 | 20 | (0.5862068965517242, 8.5) |
| pangram | 4 | 11 | (0.5862068965517242, 17.0) |
| perfect-numbers | 4 | 16 | (0.5862068965517242, 12.75) |
| space-age | 4 | 8 | (0.5862068965517242, 51.0) |
| isogram | 4 | 11 | (0.5862068965517242, 17.0) |
| protein-translation | 4 | 17 | (0.5862068965517242, 12.75) |
| sum-of-multiples | 5 | 16 | (0.5862068965517242, 17.0) |
| flatten-array | 5 | 7 | (0.5862068965517242, 51.0) |
| bottle-song | 5 | 20 | (0.5862068965517242, 17.0) |
| largest-series-product | 5 | 15 | (0.5862068965517242, 25.5) |
| allergies | 5 | 7 | (1.02, 51.0) |
| square-root | 5 | 10 | (0.5862068965517242, 51.0) |
| raindrops | 5 | 13 | (0.5862068965517242, 51.0) |
| anagram | 6 | 15 | (0.5862068965517242, 51.0) |
| atbash-cipher | 6 | 24 | (0.5862068965517242, 12.75) |
| twelve-days | 6 | 16 | (0.5862068965517242, 51.0) |
| food-chain | 7 | 26 | (0.5862068965517242, 25.5) |
| roman-numerals | 7 | 11 | (1.02, 51.0) |
| crypto-square | 7 | 23 | (0.5862068965517242, 25.5) |
| run-length-encoding | 7 | 27 | (0.5862068965517242, 17.0) |
| simple-cipher | 9 | 15 | (1.2142857142857144, 51.0) |
| saddle-points | 9 | 18 | (1.2142857142857144, 51.0) |

As you wrote most of those exercises, what do you think about this ranking @ErikSchierboom?

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
> As you wrote most of those exercises, what do you think about this ranking @ErikSchierboom?

It's generally very good, with some minor nits:

- `collatz-conjecture`: difficulty should be bumped a bit I think. I've used recursion which lead to concise code, but was a bit harder to get working than difficulty 2. Maybe a 4?
- `food-chain`: wasn't really that hard, maybe a 5?
- `simple-cipher`: should be a fair bit lower, around the `rotational-cipher` exercise's difficulty

**Comment by glaxxie** [comment]
@vaeng Most of my solution are overtly verbose, wouldn't this bump the difficulty up unnecessary?
Also I'm a bit surprised at `saddle-point` in my mind I thought it would lend itself quite nicely to the array based nature of uiua

**Comment by ErikSchierboom** [comment]
I'll go over the list a bit more tomorrow.

**Comment by ErikSchierboom** [comment]
I think `run-length-encoding` is probably the hardest one I did, so maybe we make that a 9? 

With that modified and my above suggestions, I think this is a great start. We can always re-tweak later.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
